### ISSUE TITLE
Error scope

### ISSUE THREAD

**Issue by nozurbina** [oxygenxml/dim#10]
When you have multiple errors at multiple element scopes, it's unclear. For example, when you have an error in the body ("short desc missing") and you get another error in the title, say, too many words, then you have two errors in the hoverbox with no indication where the wordcount error is referring to. It would be good to have the parentElement in front of the error so you know where to look to resolve the issue.

**Comment by georgebina** [comment]
I think this relates to the fact that some of the rules do not have a message parameter, like `restrictWords`. I will add and additional message though a parameter that you can set and thus provide more information to the user.

**Comment by georgebina** [comment]
Fixed in 376a6416220988a0eb9ccc74db70aea3b27f441b - I added a message parameter to restrictWords, restrictCharacters and restrictNumberOfChildren - please note that all instantiations of these rules need to be updated to add the message parameter with a meaningful message. In addition to that message the rules also inform the actual number of words, characters and children, respectively.
