### ISSUE TITLE
restrictCharacter params inconsistent & bug in message text

### ISSUE THREAD

**Issue by nozurbina** [oxygenxml/dim#6]
the other rules have 'parent' as their parameter name, restrictCharacters uses 'parentElement'. This cost me 30 minutes trying to figure out what I was doing wrong!

Also, when it errors it says 'you are recommended to have at least X words', instead of saying 'X characters'

**Comment by georgebina** [comment]
The restrict words also has parentElement as parameter to identify the element to be checked. I corrected the error message in 4477e9b51a6800719e6d0eefb316844043e97464.

**Comment by georgebina** [comment]
BTW, if you insert the rule though the add rule action then you should get the parameters automatically there. 
Also, to quickly identify issues, open the rules.sch file in oXygen and validate that and you should get immediately details about the actual issue. In this case, however, that will not give any error, because parent is a prefix of parentElement and in the abstract pattern context="$parentElement" will be expanded to context="titleElement" if the value of $parent is set to title. 
I logged an issue for our Schematron implementation to catch these cases and issue a warning when a parameter is used as a prefix - usually the Schema author will not want that.
